### ISSUE TITLE
Tomestone upgrades all showing as BiS

### ISSUE THREAD

**Issue by Cadwgan** [Koenari/HimbeertoniRaidTool#106]
Currently tomestone upgrades are all showing as BiS, even when no gear is detected as available.

![image](https://user-images.githubusercontent.com/8039241/201295342-6b2cf450-3333-4acf-a8ba-84ae134127aa.png)
![image](https://user-images.githubusercontent.com/8039241/201295510-298a6ccf-5311-44ea-9b7b-0a7d9cff2d0b.png)

**Comment by Koenari** [comment]
Fix will be part of version 1.1.2.x (implemented in 105b3e29de162a368ea2f49e6715955c4ae121f4)
