### ISSUE TITLE
Ui improvements

### ISSUE THREAD

**Issue by Koenari** [Koenari/HimbeertoniRaidTool#11]
If you got any feedback for improvements on the interface leave them here as a comment. Until I worked out a feedback structure this issue should work. Thank you

**Comment by Koenari** [comment]
* Add a notice to "Examine players to update level and gear"
* Add mouseovers to all clickables with short explanations

**Comment by vpcn2019** [comment]
Would it be possible to make "Current vs BiS" comparison more dynamic? As in, do not check for ordering of melds and rings (raid/tome).

**Comment by vpcn2019** [comment]
Could you please add ability to delete jobs/sets from Solo view? I got this ghost SMN just hanging around there :D
In 6.1 it was a ghost AST. I think this has something to do with how new jobs are created/populated and I think I can delete from the config files manually, but I really don't want to mess things up
![image](https://user-images.githubusercontent.com/50836814/188474057-fa35e83f-c592-48e9-8fbc-72bad735a4f7.png)

**Comment by Koenari** [comment]
Used the oprtunity to fix up player edit interface. there you will be able to easily add/delete classes. Still needs some testing and Ui optimizations but will bne in the next update
![rework](https://user-images.githubusercontent.com/7422843/188680239-86fea967-e8e2-4371-8de3-88c21e50c50f.png)

**Comment by JustMeForFun** [comment]
For me some UI elements are really crammed, could have something to do with that I'm on a 4K monitor because I have the same issue with other plugins. Other plugins allow me to manually resize windows, would be real nice if that was possible for your plugin as well :)

![afbeelding](https://user-images.githubusercontent.com/47222992/192328158-3ab09469-9be0-460b-a2f3-643e068d7a02.png)

**Comment by Koenari** [comment]
Will be working on it in #55
@JustMeForFun if you made any scaling settings apart form dalamud's Global Font Scale please let me know (comment on the issue linked above)

**Comment by Koenari** [comment]
Closing this. Everyone feel free to make individual issues
