### ISSUE TITLE
Update Gear by Examining does not work in group mode.

### ISSUE THREAD

**Issue by DeadeyeN** [Koenari/HimbeertoniRaidTool#123]
Update gear by examining does not seem to be working in group mode. I have tried using it on myself and it is not functioning - it opens the examine window in game, but does not update the gear.

**Comment by Koenari** [comment]
I cannot replicate this. I saw similar behavior while working on the 1.2 update, but was not present in the Release version and did not happen again after restarting the game. Could you let me know if this errror persists and provide me with a logfile, when this happens (I am also reachable via the Dalamud Discord)

**Comment by Koenari** [comment]
Fixed in Version 1.3.0.5
