### ISSUE TITLE
Editing bis and current raid gear is changing other lines while in group config

### ISSUE THREAD

**Issue by Ladamire** [Koenari/HimbeertoniRaidTool#124]
I have 2 members of my static that when I try and edit their Bis or current raid sets its causing the other member's gear set to change with the change that I made. I have attempted to delete the raid member from the group and re-add them same issue occurs. I attempted to remove both members however when adding them back in their gear seems to be still saved with each member having each others gear. It seems to be only happening with these two members. 

![image](https://github.com/Koenari/HimbeertoniRaidTool/assets/135044732/ab1eb530-a43f-489a-8faf-51150d458526)
Before the change
![image](https://github.com/Koenari/HimbeertoniRaidTool/assets/135044732/1fbbebad-ae2b-49ac-81c9-9b50bfd2e632)
After the change
![image](https://github.com/Koenari/HimbeertoniRaidTool/assets/135044732/ea633144-ba84-43d6-83b7-86ce20f0c703)

Editing each of the lines will change the other so I can't change one without the other changing.

**Comment by Koenari** [comment]
Fixed in cbe632d273591abc96b8d0e1784a8423b71d4ca8
