### ISSUE TITLE
Same chat command as Loot Master

### ISSUE THREAD

**Issue by Lunariya23** [Koenari/HimbeertoniRaidTool#125]
The LootMaster window won't open with /lootmaster or /lm chat command when using the "Loot Master" plugin by Aida Enna 

https://github.com/Aida-Enna/XIVPlugins/tree/main/LootMaster

even after deactivating this plugin. It uses both same commands

It works when I start the game with deactivated Loot Master plugin, but as soon as both plugins are active I can't use the RaidTool-LootMaster

I don't know if this is some kind of bug or conflict, maybe changing the chat command would be enough to solve this.

**Comment by Koenari** [comment]
You can already use /hrt lootmaster or /hrt lm.
This feature isn't well documented yet

**Comment by Lunariya23** [comment]
Thanks a lot.
