### ISSUE TITLE
HQ items not seen as HQ from Etro Import

### ISSUE THREAD

**Issue by starafar** [Koenari/HimbeertoniRaidTool#126]
Currently, if comparing to a gear/BiS list, an HQ crafted item from an Etro list is seen as an NQ item, which prevents correct matching.

Example:

Currently equipped: Diadochos Headband of Fending (HQ), DH+36/DH+36/DH+36/DH+12/DH+12
Etro list: Diadochos Headband of Fending (HQ), DH+36/DH+36/DH+36/DH+12/DH+12
Lootmaster shows from Etro list: Diadochos Headband of Fending, DH+36/DH+36/DH+36/DH+12/DH+12

These should match, but because it's importing the HQ item from Etro as NQ, it fails to match.

**Comment by Koenari** [comment]
Fixed with 2dea28292c04b43dfde18213fdcf4af12fc1a277 and will be part of Version 1.3.2.0
You will probably need to click "Update from etro.gg" for all affected BiS once the update is available
