### ISSUE TITLE
Shadowed Command Conflict (/lootmaster) with Another Plugin

### ISSUE THREAD

**Issue by aaronbcarlisle** [Koenari/HimbeertoniRaidTool#127]
`/lootmaster` is a command used in another plugin called [Loot Master](https://github.com/Aida-Enna/XIVPlugins). When both plugins are loaded, the last one that was loaded overrides the command for the other.

I'm going to leave this same feedback for Aida, but thought it was worth mentioning because it can be difficult to troubleshoot or understand why you're not getting the window you expect since there aren't any warnings/errors indicating the command overrode another's.

**Comment by Koenari** [comment]
I'm already aware. I think I have done what I can do to remediate this. See #125 for details.
I will leave this issue open and pin it for discussion and disclosure.
I'm very open for suggestions on how to handle, but a warning should propably be handled by Dalamud

**Comment by aaronbcarlisle** [comment]
Agreed on the error handling being managed by Dalamud. My only suggestion would be to update the "Welcome to HimbeerToni Raid Tool" help section via the `/hrt` command to only recommend running `/hrt lm`. This is mostly a one-off so honestly, not a big deal. Just thought it was worth mentioning. :)

**Comment by Koenari** [comment]
Changed the Welcome stuff. I consider this fixed with b2b787781068dec0371854ab6d5f6508d1a6d594
