### ISSUE TITLE
log spams error and crashes game

### ISSUE THREAD

**Issue by Kagekazu** [Koenari/HimbeertoniRaidTool#130]
Heya, 

as soon as i use /lootmaster i get an overflow of errors in my log and then my game crashes.

![image](https://github.com/Koenari/HimbeertoniRaidTool/assets/95875972/316f30da-c360-4f3a-90b6-bec6700c0f28)

this is what i get in the log ( can send more info if needed )

thanks for the awesome plugin!

**Comment by Koenari** [comment]
And tahnk you very much for the praise

**Comment by Kagekazu** [comment]
just got home, ye i was on 1.4.1.0.

i will check with the new update and see if it still does it.

i also did notice that its not loading all my presets, i made one for all classes, but it cuts off at blm

![image](https://github.com/Koenari/HimbeertoniRaidTool/assets/95875972/a89493d8-8eff-4450-863e-700f1ebc9997)

**Comment by Kagekazu** [comment]
if it helps i can try deleting the plugin/folder and reinstall to see if its a corrupt file ( i do hope i got my etro links saved somewhere :P )

**Comment by Kagekazu** [comment]
no problem. Yes it only shows up until BLM in 1.4.1.1 and it still spams the same thing in the log.

Let me know what and how to test and ill give u some more feedback :D

**Comment by Kagekazu** [comment]
just to let u know the latest update - update 1.4.1.2 - fixed the log spamming and my UI being cut off.

Thanks for the quick fixing and sorry if it caused u some trouble xD

**Comment by Koenari** [comment]
I'm glad it's fixed now, and thanks for letting me know. Always let me know when something is not working or if you have an idea or wish for a feature
