### ISSUE TITLE
Cannot add or select BIS gearset

### ISSUE THREAD

**Issue by scars377** [Koenari/HimbeertoniRaidTool#136]
I used this plugin to manage the BIS gearsets for all of the jobs but recently this stopped working.

When clicking on the `BiS` button of a job, there'd be 3 selections: `BiS(0)`, `+ Add New`, and `+ Search known sets`.

If selected `+ Add New`, I'm able to download a set from etro but after clicking "Save", nothing happens.

If selector `+ Search known sets` I'm able to see the list of saved gearsets, including the ones I chose to "make local copy" from etro, but the leading check button (with tooltip "Select gearset") has no functionality.

I've not yet found any mean that I can specify the BIS of a job and have it compared with my current gear as this plugin used to do.

**Comment by scars377** [comment]
FYI: I have deleted everything in `pluginConfigs\HimbeertoniRaidTool` and reinstall the plugin (confirmed all data been cleared) but no luck.

**Comment by Koenari** [comment]
The issues with `+ Search known sets` and `+ Add New` are fixed now.
