### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by Koenari** [Koenari/HimbeertoniRaidTool#21]
Add new Items
- ~~New raid + corresponding Item Levels~~
- ~~Boss drops~~ _preliminary_
- ~~"Currency" conversion~~
- ~~Item container contents~~
- ~~Check if item level difference stays 10 betwenn iLvl tiers~~

**Comment by KalasB** [comment]
Glad to see you're planning to support the next tier, looking forward to using it for loot distribution :). Thanks for the work.
