### ISSUE TITLE
Plugin crashing when attempting to add a player

### ISSUE THREAD

**Issue by vpcn2019** [Koenari/HimbeertoniRaidTool#25]
Hi. I started getting this issue several weeks ago, and the 6.2 update didn't change it. I tried re-installing the plugin, manually removing all local files for a "clean" run, yet every time I try to add myself under the Solo tab the plugin immediately crashes and then won't reopen. I've attached the screenshot and the relevant log
![image](https://user-images.githubusercontent.com/50836814/186894953-eaad33bf-e03f-4e98-926a-81d7ac7a83c3.png)
[HimbCrash.txt](https://github.com/Koenari/HimbeertoniRaidTool/files/9432811/HimbCrash.txt)

**Comment by Koenari** [comment]
Thank you @vpcn2019 for reporting. Please don't hesitate to report bug in the future aswell. Update is now available
