### ISSUE TITLE
Manually edit GearSets/Gear

### ISSUE THREAD

**Issue by Fivavoa** [Koenari/HimbeertoniRaidTool#32]
Any way to be able to assign gear that people are wearing manually from a drop-down or list or something without relying on something like etro or the game or lodestone? It can just be batches of raid gear instead of needing to accommodate every single piece of gear. Alternatively, there can be an option to have assigned gear be also from etro as well, so the raid leader doesn't need everyone around in order to set it up and etc.

**Comment by Koenari** [comment]
- [ ] Create interface to show and edit a gearset
- [ ] Create interface to how and edit gear item including materia
- [ ] Create structure to easily select gear (filter by iLvl, Slot, etc)

**Comment by Koenari** [comment]
Implemented Ui to edit gear manually (see screenshot). This provides functionality described above. For changes and improvements regarding the Ui please comment in #11
![EditGearDraft](https://user-images.githubusercontent.com/7422843/190482814-34c8e34e-2897-41b1-8122-4c662735854f.png)
