### ISSUE TITLE
chat command is the same is lmeter

### ISSUE THREAD

**Issue by Kagekazu** [Koenari/HimbeertoniRaidTool#48]
Is there an option to open lootmaster without /lm?

Cause i use lmeter aswell, but it also uses /lm as chatcommand.

or am i bound to uninstall lmeter if i want to use lootmaster?

**Comment by Koenari** [comment]
There is /lootmaaster which was not properly communicted in installer. Is corrected now  see b32eeab5d72d733636c2195c58f0b5fff5ed4a20
