### ISSUE TITLE
Add support for Ui/DPi scaling

### ISSUE THREAD

**Issue by Koenari** [Koenari/HimbeertoniRaidTool#55]
Fixes following issues:
1.  Ui is nearly unreadable when playing on for example a 4K TV
2. Some elemnts don't fit in the windows whaen using scaling

Note: Seems to be only affected by dalamuds "Global Font Scale"

**Comment by JustMeForFun** [comment]
I haven't made any scaling settings myself, while I do have a basic grasp on coding I don't really develop/code stuff. I'm basically just a user :P

So all I can really do is QA and/or give feedback :)
