### ISSUE TITLE
Issue: Rings and possibly other gear are distributed incorrectly

### ISSUE THREAD

**Issue by JustMeForFun** [Koenari/HimbeertoniRaidTool#80]
![afbeelding](https://user-images.githubusercontent.com/47222992/195559373-40914d6f-54b3-460f-85c1-b015a301012f.png)

Above I have a simulated scenario of 2 rings dropping from p5s. Loot rules are: DPS > Healer > Tank and then rolling.

1. The loot results return that Zuuby won over Wowisdead on both rings. In a real world scenario 2 rings wont go to the same player as they can only equip 1 of them at a time anyway.

2. On top of that both Zuuby and Wowisdead already have the raid ring. The people who should be getting the ring according to the loot rules I set up would be: Mai > Devoras > Marauder.

My suspicion is that the plugin can't see the difference between a raid and tome piece of equipment. With that in mind in this simulated scenario it does makes sense that both Zuuby and Wowisdead were at the top of the loot results as both of them are missing their 630 tome rings.

I don't know how the tome gear upgrade item drop is affected as I haven't tested that.

**Comment by Koenari** [comment]
For 1. I have thought about this but didn't find a viable solution for my code yet. I will keep information about it in #81 
I will look into 2. today

**Comment by Koenari** [comment]
2. Should be done with #83
